# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwmod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JwStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='jwcolour',
            old_name='Colour_name',
            new_name='colour_name',
        ),
    ]
