# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwmod', '0002_auto_20170824_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='JwBra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('colour_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwmod.JwColour')),
                ('style_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwmod.JwStyle')),
            ],
        ),
    ]
