# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwmod', '0004_auto_20170824_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwcolour',
            name='colour_type',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jwsize',
            name='size_name',
            field=models.CharField(max_length=20),
        ),
    ]
