# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jwmod', '0005_auto_20170824_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='JwCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='张三', max_length=20)),
                ('customer_addr', models.CharField(default='无', max_length=20)),
                ('customer_phone', models.CharField(default='无', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JwSalesBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(default=datetime.datetime(2017, 8, 24, 14, 6, 5, 106818, tzinfo=utc))),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwmod.JwCustomer')),
            ],
        ),
    ]
