# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jwmod', '0006_jwcustomer_jwsalesbill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwsalesbill',
            name='sale_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 24, 14, 9, 4, 541081, tzinfo=utc)),
        ),
    ]
