# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jwmod', '0007_auto_20170824_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwsalesbill',
            name='jwbra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jwmod.JwBra'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jwsalesbill',
            name='sale_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
