# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jwmod', '0008_auto_20170824_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwsalesbill',
            name='sale_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='jwbra',
            name='num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='jwsalesbill',
            name='sale_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 24, 14, 26, 32, 216004, tzinfo=utc)),
        ),
    ]
