# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 14:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jwmod', '0009_auto_20170824_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jwsalesbill',
            name='sale_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 25, 14, 40, 34, 815252, tzinfo=utc)),
        ),
    ]
