# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jwmod', '0010_auto_20170825_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='JwStockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('stock_date', models.DateTimeField(default=datetime.datetime(2017, 8, 26, 13, 59, 7, 942289, tzinfo=utc))),
                ('colour_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwmod.JwColour')),
                ('size_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwmod.JwSize')),
                ('style_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwmod.JwStyle')),
            ],
        ),
        migrations.AlterField(
            model_name='jwsalesbill',
            name='sale_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 26, 13, 59, 7, 944289, tzinfo=utc)),
        ),
    ]
