# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 14:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jwmod', '0015_auto_20170831_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwsalesbill',
            name='sale_price',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='jwsalesbill',
            name='sale_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 1, 14, 49, 54, 194049, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jwstocklist',
            name='stock_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 1, 14, 49, 54, 193049, tzinfo=utc)),
        ),
    ]
