# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 11:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jwmod', '0017_auto_20170901_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwbra',
            name='total',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='jwbra',
            name='num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jwsalesbill',
            name='sale_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 2, 11, 53, 6, 492826, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jwstocklist',
            name='stock_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 2, 11, 53, 6, 491826, tzinfo=utc)),
        ),
    ]
